### PR TITLE
Add getEncodedRoute api

### PR DESCRIPTION
**Pull request by nkottary**

### CODE REVIEW

**Comment by tanmaykm** [comment]
I don't think JuliaRunClient should have any dependency on JuliaBox.

Instead, the backend API can be added to JuliaRun, serviced by the JuliaRun HTTP RPC service. JuliaRun already has an exported API for this `encode_route`, which needs to be exposed via https://github.com/JuliaComputing/JuliaRun.jl/blob/master/src/remote/remote.jl.

**Comment by nkottary** [comment]
I was thinking of adding it to JuliaRun but then the config value `ROUTER_SECRET` will have to be duplicated there. It is already in 2 places: nginx.conf and juliabox conf.

Also we need to talk to juliabox to save the app name and port number in the DB so that we can show it in the UI and also track what the user has deployed.

**Comment by tanmaykm** [comment]
Yes, the secrets need to be in sync... there is no escaping that.

The encoded URL is actually encrypted data, which is decrypted by the router to get the URL to route to. So, it need not be stored in a DB.

**Comment by tanmaykm** [comment]
Here's an example of how it should work: https://github.com/JuliaComputing/JuliaRun.jl/blob/master/router/lua-juliarun-router/router.lua#L130-L143

So, as per this example, going to http://juliabox.com/app/0069a383369edea23471fcf212f8ee147cd87ca676f1f37c1b1c6a5fa0fb4229 should proxy to http://google.com/

**Pull request closed without merging**
